name: Manual Deploy with Environment Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description:
          description: "Choose environment"
          required: true
          default: "dev"
          type: choice
          options:
            - staging
            - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use API key
        run: echo "Using API Key: ${{ secrets.API_KEY }}"
