name : Secret Environment Variables

on :
  push:
    branches: [main]

jobs :
  secret-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables..."
          echo "MY_SECRET_VAR=${{ secrets.MY_SECRET_VAR }}" >> $GITHUB_ENV
          echo "MY_OTHER_SECRET_VAR=${{ secrets.MY_OTHER_SECRET_VAR }}" >> $GITHUB_ENV

      - name: Use environment variables
        run: |
          echo "Using environment variables..."
          echo "MY_SECRET_VAR is set to $MY_SECRET_VAR"
          echo "MY_OTHER_SECRET_VAR is set to $MY_OTHER_SECRET_VAR"
          echo "Above variable are displayed using the variable we set using $GITHUB_ENV"